// Workout session data for both program types

export interface WorkoutExercise {
  id: string
  name: string
  setsReps: string           // e.g. "3×15" or "2×30s"
  sets: number
  reps: string               // e.g. "15 reps" or "30 seconds"
  durationSeconds: number    // time per set
  restSeconds: number
  image: string              // main full-screen illustration
  nextImage?: string         // small preview image
  muscles: string[]
  tip: string
  category: 'warmup' | 'strength' | 'cardio' | 'core' | 'cool_down'
}

// ─────────────────────────────────────────────────────────────────
// CALISTHENICS SESSION EXERCISES
// ─────────────────────────────────────────────────────────────────
export const CALISTHENICS_SESSION: WorkoutExercise[] = [
  {
    id: 'jj',
    name: 'Jumping Jacks',
    setsReps: '2×30',
    sets: 2, reps: '30 reps',
    durationSeconds: 40, restSeconds: 20,
    image: '/artifacts/exercises/jumping_jack_illustrated.jpg',
    nextImage: '/artifacts/exercises/squat_illustrated.jpg',
    muscles: ['Full Body', 'Cardio'],
    tip: 'Land softly on the balls of your feet. Keep your core tight throughout.',
    category: 'warmup',
  },
  {
    id: 'sq',
    name: 'Bodyweight Squats',
    setsReps: '3×20',
    sets: 3, reps: '20 reps',
    durationSeconds: 45, restSeconds: 30,
    image: '/artifacts/exercises/squat_illustrated.jpg',
    nextImage: '/artifacts/exercises/pushup_illustrated.jpg',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    tip: 'Push your knees out over your toes. Keep your chest tall and heels on the floor.',
    category: 'strength',
  },
  {
    id: 'pu',
    name: 'Push-Ups',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 50, restSeconds: 40,
    image: '/artifacts/exercises/pushup_illustrated.jpg',
    nextImage: '/artifacts/exercises/mountain_climbers_illustrated.jpg',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    tip: 'Keep your body in a straight line. Lower your chest to 2cm off the floor.',
    category: 'strength',
  },
  {
    id: 'mc',
    name: 'Mountain Climbers',
    setsReps: '2×30',
    sets: 2, reps: '30 reps',
    durationSeconds: 40, restSeconds: 30,
    image: '/artifacts/exercises/mountain_climbers_illustrated.jpg',
    nextImage: '/artifacts/exercises/plank_illustrated.jpg',
    muscles: ['Core', 'Hip Flexors', 'Cardio'],
    tip: 'Drive your knees in fast but keep your hips level. Don\'t let your lower back sag.',
    category: 'cardio',
  },
  {
    id: 'pl',
    name: 'Plank Hold',
    setsReps: '3×45s',
    sets: 3, reps: '45 seconds',
    durationSeconds: 45, restSeconds: 30,
    image: '/artifacts/exercises/plank_illustrated.jpg',
    nextImage: '/artifacts/exercises/lunge_illustrated.jpg',
    muscles: ['Core', 'Shoulders', 'Glutes'],
    tip: 'Squeeze your abs and glutes hard. Breathe steadily — don\'t hold your breath.',
    category: 'core',
  },
  {
    id: 'lu',
    name: 'Forward Lunges',
    setsReps: '2×12',
    sets: 2, reps: '12 each leg',
    durationSeconds: 50, restSeconds: 40,
    image: '/artifacts/exercises/lunge_illustrated.jpg',
    nextImage: '/artifacts/exercises/crunch_illustrated.jpg',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    tip: 'Keep your front knee directly above your ankle. Tall chest, don\'t lean forward.',
    category: 'strength',
  },
  {
    id: 'cr',
    name: 'Crunches',
    setsReps: '3×20',
    sets: 3, reps: '20 reps',
    durationSeconds: 40, restSeconds: 30,
    image: '/artifacts/exercises/crunch_illustrated.jpg',
    nextImage: '/artifacts/exercises/superman_illustrated.jpg',
    muscles: ['Rectus Abdominis', 'Core'],
    tip: 'Curl your shoulders off the floor — this isn\'t a full sit-up. Feel the squeeze at the top.',
    category: 'core',
  },
  {
    id: 'sm',
    name: 'Superman',
    setsReps: '3×20',
    sets: 3, reps: '20 reps',
    durationSeconds: 45, restSeconds: 30,
    image: '/artifacts/exercises/superman_illustrated.jpg',
    nextImage: '/artifacts/exercises/high_knees_illustrated.jpg',
    muscles: ['Lower Back', 'Glutes', 'Rear Deltoids'],
    tip: 'Lift slowly and hold for 1 second at the top. This protects your lower back.',
    category: 'core',
  },
  {
    id: 'hk',
    name: 'High Knees',
    setsReps: '3×30',
    sets: 3, reps: '30 reps',
    durationSeconds: 35, restSeconds: 25,
    image: '/artifacts/exercises/high_knees_illustrated.jpg',
    nextImage: '/artifacts/exercises/burpee_illustrated.jpg',
    muscles: ['Hip Flexors', 'Quads', 'Cardio'],
    tip: 'Drive your knees above hip height each rep. Pump your arms for speed.',
    category: 'cardio',
  },
  {
    id: 'bu',
    name: 'Burpees',
    setsReps: '2×10',
    sets: 2, reps: '10 reps',
    durationSeconds: 50, restSeconds: 45,
    image: '/artifacts/exercises/burpee_illustrated.jpg',
    nextImage: '/artifacts/exercises/glute_bridge_illustrated.jpg',
    muscles: ['Full Body', 'Cardio', 'Core'],
    tip: 'Explosively jump at the top with arms overhead. Step back instead of jumping if needed.',
    category: 'cardio',
  },
  {
    id: 'gb',
    name: 'Glute Bridge',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 40, restSeconds: 30,
    image: '/artifacts/exercises/glute_bridge_illustrated.jpg',
    nextImage: '/artifacts/exercises/side_plank_illustrated.jpg',
    muscles: ['Glutes', 'Hamstrings', 'Lower Back'],
    tip: 'Squeeze your glutes hard at the top and hold 1 second. Drive through your heels.',
    category: 'strength',
  },
  {
    id: 'sp',
    name: 'Side Plank',
    setsReps: '2×30s',
    sets: 2, reps: '30 sec each side',
    durationSeconds: 30, restSeconds: 20,
    image: '/artifacts/exercises/side_plank_illustrated.jpg',
    nextImage: '/artifacts/exercises/vsit_illustrated.jpg',
    muscles: ['Obliques', 'Core', 'Glutes'],
    tip: 'Stack your feet or stagger them. Keep your hips lifted — don\'t sag.',
    category: 'core',
  },
  {
    id: 'vs',
    name: 'V-Sit Hold',
    setsReps: '3×20s',
    sets: 3, reps: '20 seconds',
    durationSeconds: 20, restSeconds: 30,
    image: '/artifacts/exercises/vsit_illustrated.jpg',
    nextImage: '/artifacts/exercises/leg_raise_illustrated.jpg',
    muscles: ['Core', 'Hip Flexors', 'Abs'],
    tip: 'Balance on your tailbone. If too hard, bend your knees slightly.',
    category: 'core',
  },
  {
    id: 'lr',
    name: 'Leg Raises',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 40, restSeconds: 30,
    image: '/artifacts/exercises/leg_raise_illustrated.jpg',
    nextImage: '/artifacts/exercises/jumping_jack_illustrated.jpg',
    muscles: ['Lower Abs', 'Hip Flexors'],
    tip: 'Keep your lower back pressed flat to the ground. Lower legs slowly without touching the floor.',
    category: 'core',
  },
]

// ─────────────────────────────────────────────────────────────────
// GYM SESSION EXERCISES
// ─────────────────────────────────────────────────────────────────
export const GYM_SESSION: WorkoutExercise[] = [
  {
    id: 'tw',
    name: 'Treadmill Walk',
    setsReps: '1×5 min',
    sets: 1, reps: '5 minutes',
    durationSeconds: 300, restSeconds: 0,
    image: '/artifacts/exercises/recumbent_bike_illustrated.jpg',
    nextImage: '/artifacts/exercises/hip_mobility_illustrated.jpg',
    muscles: ['Cardio', 'Calves', 'Quads'],
    tip: 'Start at 3 km/h, clip the safety tether to your shirt before pressing START.',
    category: 'warmup',
  },
  {
    id: 'sc',
    name: 'Shoulder Circles',
    setsReps: '1×20',
    sets: 1, reps: '10 fwd + 10 back',
    durationSeconds: 60, restSeconds: 0,
    image: '/artifacts/exercises/hip_mobility_illustrated.jpg',
    nextImage: '/artifacts/exercises/leg_press_illustrated.jpg',
    muscles: ['Shoulders', 'Rotator Cuff'],
    tip: 'Slow, controlled circles. Feel the shoulder joints warming up — no pain.',
    category: 'warmup',
  },
  {
    id: 'lp',
    name: 'Leg Press',
    setsReps: '2×12',
    sets: 2, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/leg_press_illustrated.jpg',
    nextImage: '/artifacts/exercises/chest_press_illustrated.jpg',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    tip: 'Feet shoulder-width apart. Lower to 90° knee bend. Press through your heels, not your toes.',
    category: 'strength',
  },
  {
    id: 'cp',
    name: 'Chest Press',
    setsReps: '2×12',
    sets: 2, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/chest_press_illustrated.jpg',
    nextImage: '/artifacts/exercises/seated_row_illustrated.jpg',
    muscles: ['Chest', 'Front Delts', 'Triceps'],
    tip: 'Adjust seat so handles align with mid-chest. Keep shoulders pressed down, not shrugged up.',
    category: 'strength',
  },
  {
    id: 'sr',
    name: 'Seated Cable Row',
    setsReps: '2×12',
    sets: 2, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/seated_row_illustrated.jpg',
    nextImage: '/artifacts/exercises/lat_pulldown_illustrated.jpg',
    muscles: ['Rhomboids', 'Lats', 'Biceps'],
    tip: 'Pull the handle to your navel. Squeeze your shoulder blades together at the back.',
    category: 'strength',
  },
  {
    id: 'lpd',
    name: 'Lat Pulldown',
    setsReps: '2×12',
    sets: 2, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/lat_pulldown_illustrated.jpg',
    nextImage: '/artifacts/exercises/leg_extension_illustrated.jpg',
    muscles: ['Lats', 'Teres Major', 'Biceps'],
    tip: 'Always pull to the front — never behind the neck. Lead with your elbows pulling down.',
    category: 'strength',
  },
  {
    id: 'le',
    name: 'Leg Extension',
    setsReps: '2×15',
    sets: 2, reps: '15 reps',
    durationSeconds: 45, restSeconds: 90,
    image: '/artifacts/exercises/leg_extension_illustrated.jpg',
    nextImage: '/artifacts/exercises/leg_curl_illustrated.jpg',
    muscles: ['Quadriceps'],
    tip: 'Extend fully and squeeze quads at the top. Lower slowly — 3 seconds down.',
    category: 'strength',
  },
  {
    id: 'lc',
    name: 'Seated Leg Curl',
    setsReps: '2×15',
    sets: 2, reps: '15 reps',
    durationSeconds: 45, restSeconds: 90,
    image: '/artifacts/exercises/leg_curl_illustrated.jpg',
    nextImage: '/artifacts/exercises/shoulder_press_illustrated.jpg',
    muscles: ['Hamstrings', 'Calves'],
    tip: 'Keep hips flat on the seat. Curl all the way back and hold 1 second.',
    category: 'strength',
  },
  {
    id: 'shp',
    name: 'Shoulder Press',
    setsReps: '2×12',
    sets: 2, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/shoulder_press_illustrated.jpg',
    nextImage: '/artifacts/exercises/tricep_pressdown_illustrated.jpg',
    muscles: ['Deltoids', 'Triceps', 'Upper Traps'],
    tip: 'Press straight up without arching your lower back. Exhale as you press.',
    category: 'strength',
  },
  {
    id: 'tp',
    name: 'Tricep Pressdown',
    setsReps: '2×15',
    sets: 2, reps: '15 reps',
    durationSeconds: 45, restSeconds: 60,
    image: '/artifacts/exercises/tricep_pressdown_illustrated.jpg',
    nextImage: '/artifacts/exercises/cable_fly_illustrated.jpg',
    muscles: ['Triceps'],
    tip: 'Keep your elbows glued to your sides. Press all the way down until arms are straight.',
    category: 'strength',
  },
  {
    id: 'cf',
    name: 'Cable Fly',
    setsReps: '2×15',
    sets: 2, reps: '15 reps',
    durationSeconds: 45, restSeconds: 60,
    image: '/artifacts/exercises/cable_fly_illustrated.jpg',
    nextImage: '/artifacts/exercises/recumbent_bike_illustrated.jpg',
    muscles: ['Chest', 'Front Deltoids'],
    tip: 'Keep a slight bend in the elbows throughout. Feel the stretch and squeeze in your chest.',
    category: 'strength',
  },
  {
    id: 'cd',
    name: 'Cool-Down Bike',
    setsReps: '1×5 min',
    sets: 1, reps: '5 minutes easy',
    durationSeconds: 300, restSeconds: 0,
    image: '/artifacts/exercises/recumbent_bike_illustrated.jpg',
    nextImage: '/artifacts/exercises/hip_mobility_illustrated.jpg',
    muscles: ['Cardio', 'Recovery'],
    tip: 'Pedal gently at zero resistance. Let your heart rate drop naturally.',
    category: 'cool_down',
  },
]
