// Workout session data for both program types

export interface WorkoutExercise {
  id: string
  name: string
  setsReps: string           // e.g. "3×15" or "2×30s"
  sets: number
  reps: string               // e.g. "15 reps" or "30 seconds"
  durationSeconds: number    // time per set
  restSeconds: number
  image: string              // main full-screen illustration / animated GIF
  motionGif?: string         // looping animated GIF for motion coach
  nextImage?: string         // small preview image
  muscles: string[]
  tip: string
  category: 'warmup' | 'strength' | 'cardio' | 'core' | 'cool_down'
}

// ─────────────────────────────────────────────────────────────────
// CALISTHENICS SESSION EXERCISES
// ─────────────────────────────────────────────────────────────────
export const CALISTHENICS_SESSION: WorkoutExercise[] = [
  {
    id: 'jj',
    name: 'Jumping Jacks',
    setsReps: '2×30',
    sets: 2, reps: '30 reps',
    durationSeconds: 40, restSeconds: 20,
    image: '/artifacts/morning-challenge/jumping_jacks_motion.gif',
    motionGif: '/artifacts/morning-challenge/jumping_jacks_motion.gif',
    nextImage: '/artifacts/morning-challenge/squats_motion.gif',
    muscles: ['Full Body', 'Cardio'],
    tip: 'Land softly on the balls of your feet. Keep your core tight throughout.',
    category: 'warmup',
  },
  {
    id: 'sq',
    name: 'Bodyweight Squats',
    setsReps: '3×20',
    sets: 3, reps: '20 reps',
    durationSeconds: 45, restSeconds: 30,
    image: '/artifacts/morning-challenge/squats_motion.gif',
    motionGif: '/artifacts/morning-challenge/squats_motion.gif',
    nextImage: '/artifacts/morning-challenge/push_up_motion.gif',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    tip: 'Push your knees out over your toes. Keep your chest tall and heels on the floor.',
    category: 'strength',
  },
  {
    id: 'pu',
    name: 'Push-Ups',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 50, restSeconds: 40,
    image: '/artifacts/morning-challenge/push_up_motion.gif',
    motionGif: '/artifacts/morning-challenge/push_up_motion.gif',
    nextImage: '/artifacts/morning-challenge/mountain_climbers_motion.gif',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    tip: 'Keep your body in a straight line. Lower your chest to 2cm off the floor.',
    category: 'strength',
  },
  {
    id: 'mc',
    name: 'Mountain Climbers',
    setsReps: '3×20',
    sets: 3, reps: '20 each leg',
    durationSeconds: 40, restSeconds: 30,
    image: '/artifacts/morning-challenge/mountain_climbers_motion.gif',
    motionGif: '/artifacts/morning-challenge/mountain_climbers_motion.gif',
    nextImage: '/artifacts/morning-challenge/plank_motion.gif',
    muscles: ['Core', 'Hip Flexors', 'Cardio'],
    tip: 'Drive knees straight to chest in a rapid rhythm. Don\'t let hips bounce.',
    category: 'cardio',
  },
  {
    id: 'pl',
    name: 'Forearm Plank',
    setsReps: '3×30s',
    sets: 3, reps: '30 seconds',
    durationSeconds: 30, restSeconds: 30,
    image: '/artifacts/morning-challenge/plank_motion.gif',
    motionGif: '/artifacts/morning-challenge/plank_motion.gif',
    nextImage: '/artifacts/morning-challenge/lunges_motion.gif',
    muscles: ['Abs', 'Obliques', 'Lower Back'],
    tip: 'Brace your core like someone is about to punch your stomach. Squeeze glutes.',
    category: 'core',
  },
  {
    id: 'lu',
    name: 'Forward Lunges',
    setsReps: '2×12',
    sets: 2, reps: '12 each leg',
    durationSeconds: 50, restSeconds: 40,
    image: '/artifacts/morning-challenge/lunges_motion.gif',
    motionGif: '/artifacts/morning-challenge/lunges_motion.gif',
    nextImage: '/artifacts/morning-challenge/crunches_motion.gif',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    tip: 'Keep your front knee directly above your ankle. Tall chest, don\'t lean forward.',
    category: 'strength',
  },
  {
    id: 'cr',
    name: 'Crunches',
    setsReps: '3×20',
    sets: 3, reps: '20 reps',
    durationSeconds: 40, restSeconds: 30,
    image: '/artifacts/morning-challenge/crunches_motion.gif',
    motionGif: '/artifacts/morning-challenge/crunches_motion.gif',
    nextImage: '/artifacts/morning-challenge/superman_motion.gif',
    muscles: ['Rectus Abdominis', 'Core'],
    tip: 'Curl your shoulders off the floor — this isn\'t a full sit-up. Feel the squeeze at the top.',
    category: 'core',
  },
  {
    id: 'sm',
    name: 'Superman',
    setsReps: '3×20',
    sets: 3, reps: '20 reps',
    durationSeconds: 45, restSeconds: 30,
    image: '/artifacts/morning-challenge/superman_motion.gif',
    motionGif: '/artifacts/morning-challenge/superman_motion.gif',
    nextImage: '/artifacts/morning-challenge/high_knees_motion.gif',
    muscles: ['Lower Back', 'Glutes', 'Rear Deltoids'],
    tip: 'Lift slowly and hold for 1 second at the top. This protects your lower back.',
    category: 'core',
  },
  {
    id: 'hk',
    name: 'High Knees',
    setsReps: '3×30',
    sets: 3, reps: '30 reps',
    durationSeconds: 35, restSeconds: 25,
    image: '/artifacts/morning-challenge/high_knees_motion.gif',
    motionGif: '/artifacts/morning-challenge/high_knees_motion.gif',
    nextImage: '/artifacts/morning-challenge/burpees_motion.gif',
    muscles: ['Hip Flexors', 'Quads', 'Cardio'],
    tip: 'Drive your knees above hip height each rep. Pump your arms for speed.',
    category: 'cardio',
  },
  {
    id: 'bu',
    name: 'Burpees',
    setsReps: '2×10',
    sets: 2, reps: '10 reps',
    durationSeconds: 50, restSeconds: 45,
    image: '/artifacts/morning-challenge/burpees_motion.gif',
    motionGif: '/artifacts/morning-challenge/burpees_motion.gif',
    nextImage: '/artifacts/morning-challenge/glute_bridge_motion.gif',
    muscles: ['Full Body', 'Cardio', 'Core'],
    tip: 'Explosively jump at the top with arms overhead. Step back instead of jumping if needed.',
    category: 'cardio',
  },
  {
    id: 'gb',
    name: 'Glute Bridge',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 40, restSeconds: 30,
    image: '/artifacts/morning-challenge/glute_bridge_motion.gif',
    motionGif: '/artifacts/morning-challenge/glute_bridge_motion.gif',
    nextImage: '/artifacts/morning-challenge/side_plank_motion.gif',
    muscles: ['Glutes', 'Hamstrings', 'Lower Back'],
    tip: 'Squeeze your glutes hard at the top and hold 1 second. Drive through your heels.',
    category: 'strength',
  },
  {
    id: 'sp',
    name: 'Side Plank',
    setsReps: '2×30s',
    sets: 2, reps: '30 sec each side',
    durationSeconds: 30, restSeconds: 20,
    image: '/artifacts/morning-challenge/side_plank_motion.gif',
    motionGif: '/artifacts/morning-challenge/side_plank_motion.gif',
    nextImage: '/artifacts/morning-challenge/bicycle_crunches_motion.gif',
    muscles: ['Obliques', 'Core', 'Glutes'],
    tip: 'Stack your feet or stagger them. Keep your hips lifted — don\'t sag.',
    category: 'core',
  },
]

// ─────────────────────────────────────────────────────────────────
// GYM SESSION EXERCISES (WITH ANIMATED MOTION GIFS)
// ─────────────────────────────────────────────────────────────────
export const GYM_SESSION: WorkoutExercise[] = [
  {
    id: 'tw',
    name: 'Treadmill Walk (Warm-Up)',
    setsReps: '1×5 min',
    sets: 1, reps: '5 minutes',
    durationSeconds: 300, restSeconds: 0,
    image: '/artifacts/exercises/treadmill_walk_motion.gif',
    motionGif: '/artifacts/exercises/treadmill_walk_motion.gif',
    nextImage: '/artifacts/exercises/shoulder_circles_motion.gif',
    muscles: ['Cardio', 'Calves', 'Quads'],
    tip: 'Start at 3–4 km/h to gently raise body temperature and increase joint lubrication.',
    category: 'warmup',
  },
  {
    id: 'sc',
    name: 'Shoulder Circles (Mobility)',
    setsReps: '1×20',
    sets: 1, reps: '10 fwd + 10 back',
    durationSeconds: 60, restSeconds: 0,
    image: '/artifacts/exercises/shoulder_circles_motion.gif',
    motionGif: '/artifacts/exercises/shoulder_circles_motion.gif',
    nextImage: '/artifacts/exercises/leg_press_motion.gif',
    muscles: ['Shoulders', 'Rotator Cuff'],
    tip: 'Slow, controlled circles. Feel the shoulder joints warming up — no clicking or strain.',
    category: 'warmup',
  },
  {
    id: 'lp',
    name: 'Leg Press Machine',
    setsReps: '3×12',
    sets: 3, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/leg_press_motion.gif',
    motionGif: '/artifacts/exercises/leg_press_motion.gif',
    nextImage: '/artifacts/exercises/chest_press_motion.gif',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    tip: 'Feet shoulder-width apart. Lower to 90° knee bend. Press through full foot, do not lock knees.',
    category: 'strength',
  },
  {
    id: 'cp',
    name: 'Seated Chest Press Machine',
    setsReps: '3×12',
    sets: 3, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/chest_press_motion.gif',
    motionGif: '/artifacts/exercises/chest_press_motion.gif',
    nextImage: '/artifacts/exercises/seated_row_motion.gif',
    muscles: ['Chest', 'Front Delts', 'Triceps'],
    tip: 'Adjust seat so handles align with mid-chest. Exhale as you push forward, 2s controlled return.',
    category: 'strength',
  },
  {
    id: 'sr',
    name: 'Seated Cable Row',
    setsReps: '3×12',
    sets: 3, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/seated_row_motion.gif',
    motionGif: '/artifacts/exercises/seated_row_motion.gif',
    nextImage: '/artifacts/exercises/lat_pulldown_motion.gif',
    muscles: ['Rhomboids', 'Lats', 'Biceps'],
    tip: 'Pull handle smoothly toward your navel. Squeeze your shoulder blades together at peak pull.',
    category: 'strength',
  },
  {
    id: 'lpd',
    name: 'Neutral-Grip Lat Pulldown',
    setsReps: '3×12',
    sets: 3, reps: '12 reps',
    durationSeconds: 50, restSeconds: 90,
    image: '/artifacts/exercises/lat_pulldown_motion.gif',
    motionGif: '/artifacts/exercises/lat_pulldown_motion.gif',
    nextImage: '/artifacts/exercises/leg_extension_motion.gif',
    muscles: ['Lats', 'Teres Major', 'Biceps'],
    tip: 'Pull the bar down toward upper chest. Lead with elbows driving down and slightly back.',
    category: 'strength',
  },
  {
    id: 'le',
    name: 'Leg Extension Machine',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 45, restSeconds: 90,
    image: '/artifacts/exercises/leg_extension_motion.gif',
    motionGif: '/artifacts/exercises/leg_extension_motion.gif',
    nextImage: '/artifacts/exercises/seated_leg_curl_motion.gif',
    muscles: ['Quadriceps'],
    tip: 'Extend fully and pause 1s at top to maximize quad contraction. 3s controlled lowering.',
    category: 'strength',
  },
  {
    id: 'lc',
    name: 'Seated Leg Curl Machine',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 45, restSeconds: 90,
    image: '/artifacts/exercises/seated_leg_curl_motion.gif',
    motionGif: '/artifacts/exercises/seated_leg_curl_motion.gif',
    nextImage: '/artifacts/exercises/triceps_pressdown_motion.gif',
    muscles: ['Hamstrings', 'Calves'],
    tip: 'Keep hips firmly against backrest. Curl down smoothly and feel the hamstring engagement.',
    category: 'strength',
  },
  {
    id: 'tp',
    name: 'Cable Triceps Press-Down',
    setsReps: '3×15',
    sets: 3, reps: '15 reps',
    durationSeconds: 45, restSeconds: 60,
    image: '/artifacts/exercises/triceps_pressdown_motion.gif',
    motionGif: '/artifacts/exercises/triceps_pressdown_motion.gif',
    nextImage: '/artifacts/exercises/recumbent_bike_motion.gif',
    muscles: ['Triceps'],
    tip: 'Pin elbows to your ribs. Press straight down and lock out your triceps at the bottom.',
    category: 'strength',
  },
  {
    id: 'rb',
    name: 'Recumbent Bike (Cool-Down)',
    setsReps: '1×10 min',
    sets: 1, reps: '10 minutes',
    durationSeconds: 600, restSeconds: 0,
    image: '/artifacts/exercises/recumbent_bike_motion.gif',
    motionGif: '/artifacts/exercises/recumbent_bike_motion.gif',
    nextImage: undefined,
    muscles: ['Cardio', 'Recovery'],
    tip: 'Pedal gently at low resistance. Let your heart rate and breathing return to baseline.',
    category: 'cool_down',
  },
]

